config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :posts do
    member do
      resources :comments
    end
  end
  devise_for :users
  resources :roles
  resources :users

  get 'admin/dashboard'
  get 'admin/posts' => 'admin#posts'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :post, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 5

  belongs_to :type
  belongs_to :user
  has_many   :comments

 	validates  :type, :title, :description, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
	validates :name, presence: true
	has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	validates :username, presence: true, uniqueness: true
  has_many :posts
 	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :username
    end

  private
    def after_sign_in_path_for(resource)
      posts_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_post

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@post)
  end

  private
  def find_post
    @post = current_user.posts.find(params[:id]) if params[:id]
  end

  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = current_user.posts.order('created_at')
  end

  def show
    @comment = @post.comments.new
  end

  def new
    @post = current_user.posts.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:type_id, :user_id, :title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	end

	def edit
		@user = current_user
	end

	def update
		current_user.update(user_params)
		redirect_to user_path(current_user)
	end

	private
		def user_params
      params.require(:user).permit(	:first_name, :last_name, :date_of_birth, :street_1, :street_2,
      															:city, :state, :country, :zip_code)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if params[:search]
  		type = Type.where('lower(name) = ?', params[:search].downcase).first
	  	@posts = type.posts.order('created_at desc').page params[:page]
  	else
  		@posts = Post.order('created_at desc').page params[:page]
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blogger</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/shared/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/shared/footer' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Blogger 2017</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Blogger</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<%= root_path %>">Home</a>
        </li>

        <% if user_signed_in? %>
        <li>
          <a href="<%= user_path(current_user) %>">Profile</a>
        </li>

        <li>
          <a href="<%= posts_path %>">Posts</a>
        </li>
        <% else %>
        <li>
          <a href="<%= root_path %>">Posts</a>
        </li>
        <% end %>

        <% if user_signed_in? %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to raw('<span class="fa fa-sign-in" aria-hidden="true"></span> Sign In'), new_user_session_path %>
        </li>
        <li>
          <%= link_to raw('<span class="fa fa-user" aria-hidden="true"></span> Sign Up'), new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<header class="intro-header" style="background-image: url('/assets/hd_laptop_backgrounds.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Keep blogging</h1>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :type_id %><br>
    <%= f.select :type_id, Type.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Please select post type'}, class: 'form-control' %>

  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control', placeholder: "Give title to your post" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', rows: 10, placeholder: "Describe post" %>
  </div>
  <div class="actions">
    <%= f.submit "Publish Post", class: 'btn btn-primary' %>
    <%= link_to 'Back', posts_path %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Type</th>
        <th>User</th>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.type.name.capitalize if post.type %></td>
          <td><%= post.user.username %></td>
          <td><%= post.title %></td>
          <td><%= post.description.truncate(150) %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New post', new_post_path, :class => 'btn btn-success' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @post.type.name.capitalize if @post.type %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username.capitalize %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@post.description) %>
</p>
<% if user_signed_in? %>
	<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-success' %>
	<%= link_to 'Back', posts_path %>
<% else %>
	<%= link_to 'Back', :back, class: 'btn btn-danger' %>
<% end %>

<hr>
<h3>Discussion</h3>
<br>
<% @post.comments.order('created_at').each do |comment| %>
  <% if !comment.id.nil? %>
  <blockquote class="blockquote">
    <p>
      <%= comment.body %>
      <br>
      <small>by, <strong>
            <%= comment.user.username %>
            </strong>
      </small>
    </p>
  </blockquote>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= form_for @comment do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= f.submit "Post Comment", class: "btn btn-info" %>
    </div>
  <% end %>
<% else %>
  <h4>Please <%= link_to "Login", new_user_session_path, style: "color: #d43f3a;" %> to Discuss.</h4>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control', placeholder: "First Name" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control', placeholder: "Last Name" %>
  </div>

  <div class="form-group">
    <%= f.label :about_me %><br>
    <%= f.text_area :about_me, class: 'form-control', placeholder: "About me" %>
  </div>

  <div class="actions">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
    <%= link_to 'Back', posts_path %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
   <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-2 toppad" >
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><%= current_user.email %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class=" col-md-12 col-lg-12 "> 
            <table class="table table-user-information">
              <tbody>
                <tr>
                  <td>Username:</td>
                  <td><%= current_user.username %></td>
                </tr>

                <tr>
                  <td>Name:</td>
                  <td><%= current_user.first_name %> <%= current_user.last_name %></td>
                </tr>

              	<tr>
                	<td>About Me</td>
                	<td>
                		<%= current_user.about_me %>
                	</td>
              	</tr>
              </tbody>
            </table>
            <div class="text-center">
            <a href="<%= edit_user_path(current_user) %>" class="btn btn-success">Edit Profile</a>
						<a href="<%= edit_user_registration_path %>" class="btn btn-primary">Account Setting</a>            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <% @posts.each do |post| %>
    <div class="post-preview">
      <a href="<%= post_url(post) %>">
        <h2 class="post-title">
          <%= post.title.capitalize if post.title %>
        </h2>
      </a>
      <p class="post-meta">Posted by <a href="#"><%= post.user.username %></a> on <%= post.created_at.strftime("%B %d, %Y") %><br />
        Tag : <a href="<%= root_url(:search => post.type.name) %>"><%= post.type.name %></a>
      </p>
    </div>
    <hr>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>